# -*- coding: utf-8 -*-
"""Ai Based Job Market Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gi_aW-gmLbFq1tbnVtQJ4InXAmY0yFxC
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt #import all the libraries

df=pd.read_csv('job_descriptions.csv') # Load Dataset

df

df.shape

df.head(5)

df.tail(5)

df.info()

df.describe()

df.isnull().sum()

df[df.duplicated()]

df['Job Id'].value_counts()

for col in df.columns:
  if df[col].nunique() < 20:
    print(df[col].value_counts())
    print("-"*50)

df['Company Profile'] = df['Company Profile'].fillna('Unknown')

df.isnull().sum()

for col in df.columns:
    count = (df[col].astype(str) != df[col].astype(str).str.strip()).sum()
    if count > 0:
        print(col, "->", count)   # check columns space is available or not

df['Job Posting Date']

df['Job Posting Date']=pd.to_datetime(df['Job Posting Date'])

df['Job Posting Date']

numerical_cols = df.select_dtypes(include=np.number).columns.tolist()
print(f"Numerical columns identified for outlier detection: {numerical_cols}")

cols = ['Job Id', 'latitude', 'longitude', 'Company Size']

plt.figure(figsize=(12, 10)) # Adjusted figure size for 2x2 subplots
for i, col in enumerate (cols, 1):
    plt.subplot(2, 2, i) # Changed subplot layout to 2 rows, 2 columns
    sns.boxplot(y=df[col], color='skyblue', width=0.3)
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.ylabel("")
    plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

from scipy import stats

import numpy as np
z_scores = np.abs(stats.zscore(df['longitude']))

df_clean = df[~(z_scores > 3)]

cols = ['Job Id', 'latitude', 'longitude', 'Company Size']

plt.figure(figsize=(12, 10)) # Adjusted figure size for 2x2 subplots
for i, col in enumerate (cols, 1):
    plt.subplot(2, 2, i) # Changed subplot layout to 2 rows, 2 columns
    sns.boxplot(y=df_clean[col], color='skyblue', width=0.3)
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.ylabel("")
    plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

print(f"Total number of rows: {df.shape[0]}") # To display total number of rows

df.dtypes

plt.figure(figsize=(12, 15))
sns.countplot(y='Job Title', data=df, order=df['Job Title'].value_counts().index[:50])
plt.title('Top 50 Job Title Counts')
plt.xlabel('Count')
plt.ylabel('Job Title')
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 8)) # Adjust figure size for better readability of vertical bars
sns.countplot(x='Job Portal', data=df, order=df['Job Portal'].value_counts().index)
plt.title('Job Portal Counts (Vertical Bar Plot)')
plt.xlabel('Job Portal')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

sns.kdeplot(df['latitude'], fill=True)
plt.title('KDE Plot of Company Size')
plt.show()

sns.kdeplot(df['longitude'], fill=True)
plt.title('KDE Plot of Company Size')
plt.show()

df['year'] = df['Job Posting Date'].dt.year

year_title = df.groupby(['year', 'Job Title']).size().reset_index(name='count')

top50_per_year = (
    year_title
    .sort_values(['year', 'count'], ascending=[True, False])
    .groupby('year')
    .head(50)
)

plt.figure(figsize=(18,8))

sns.barplot(
    x='Job Title',
    y='count',
    hue='year',
    data=top50_per_year,
    palette='Set2'
)

plt.xticks(rotation=90)
plt.title('Top 50 Job Titles Year-wise')
plt.xlabel('Job Title')
plt.ylabel('Count')

plt.show()

df.head()

pd.set_option('display.max_columns', None)
display(df.head()) # To display all columns

df.to_csv('cleaned_data_Job_description.csv', index=False)

def convert_experience(exp):
    if pd.isnull(exp):
        return None

    exp = exp.lower().replace('years', '').strip()
    parts = exp.split('to')

    try:
        nums = [int(p.strip()) for p in parts]
        return sum(nums) / len(nums)
    except:
        return None

df['experience_num'] = df['Experience'].apply(convert_experience)  # Convert experience into numeric

df['experience_num']

def convert_salary(sal):
    if pd.isnull(sal):
        return None

    sal = sal.replace('$', '').replace('K', '')
    parts = sal.split('-')

    try:
        nums = [float(p.strip()) for p in parts]
        return sum(nums) / len(nums)
    except:
        return None

df['salary_num'] = df['Salary Range'].apply(convert_salary)  # Convert salary into numeric column

df['salary_num']

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['location_encoded'] = le.fit_transform(df['location'])

df['skills'] = df['skills'].str.lower()
df['skills'] = df['skills'].str.replace('[^a-zA-Z, ]', '', regex=True)
df['skills'] = df['skills'].str.replace(',', ' ')

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=1000)
skills_matrix = tfidf.fit_transform(df['skills'])

from scipy.sparse import hstack

numeric_features = df[['experience_num', 'location_encoded']]

X = hstack([skills_matrix, numeric_features])
y = df['salary_num']

from scipy.sparse import hstack

X = hstack([skills_matrix, df[['experience_num', 'location_encoded']]])
y = df['salary_num']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)







